-- remove table if it exists
drop table if exists bookmark;

-- creat the table anew
create table bookmark (
    id INTEGER primary key generated by default as identity,
    title text not null,
    describe text,
    rating numeric
);

-- insert some test data
-- using a multi-row insert statement here
insert into bookmark (title, describe, rating)
values
('Keith', 'story', 9),
('Mika', 'story', 9),
('Kai', 'story', 9),
('Li', 'story', 9),
('Chickpea', 'story', 9),
('Dumont', 'story', 9),
('endof', 'story', 9)

