DROP TABLE IF EXISTS supplier CASCADE;

CREATE TABLE supplier (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    supplier_name TEXT NOT NULL,
    phone TEXT, 
    city TEXT
);

DROP TABLE IF EXISTS item CASCADE;

CREATE TABLE item (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL,
    unit TEXT, 
    unit_cost numeric,
    supplier INTEGER REFERENCES supplier(id) ON DELETE SET NULL 
    /* creates supplier column that is a foreign key to the id column of the supplier table
        <column name> <data type> REFERENCES <foreign table name>(<foreign column>) */
);

DROP TABLE IF EXISTS supplier_order CASCADE;

CREATE TABLE supplier_order (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_date DATE DEFAULT now(),
    item INTEGER REFERENCES item(id) ON DELETE CASCADE NOT NULL,
    amount numeric,
    total_cost numeric, 
    shipping_status TEXT
);